// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9EZwuD8UZ02S4-48YhAc2Ixf9z3Ge7Wc',
    appId: '1:619732410479:web:4d3be74ac6f12f1a4d2d9a',
    messagingSenderId: '619732410479',
    projectId: 'bigtoy-dde0f',
    authDomain: 'bigtoy-dde0f.firebaseapp.com',
    storageBucket: 'bigtoy-dde0f.appspot.com',
    measurementId: 'G-THN3FTQ4RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJulgsa4vVeUna06NHAGupXkbb5ljLW0',
    appId: '1:619732410479:android:55aa9da8a060ccb44d2d9a',
    messagingSenderId: '619732410479',
    projectId: 'bigtoy-dde0f',
    storageBucket: 'bigtoy-dde0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8L2RC62HpOgKbuwHTtr7938z94Qu61M0',
    appId: '1:619732410479:ios:9054fbfeb92ffcd94d2d9a',
    messagingSenderId: '619732410479',
    projectId: 'bigtoy-dde0f',
    storageBucket: 'bigtoy-dde0f.appspot.com',
    iosBundleId: 'com.example.bigtoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8L2RC62HpOgKbuwHTtr7938z94Qu61M0',
    appId: '1:619732410479:ios:9054fbfeb92ffcd94d2d9a',
    messagingSenderId: '619732410479',
    projectId: 'bigtoy-dde0f',
    storageBucket: 'bigtoy-dde0f.appspot.com',
    iosBundleId: 'com.example.bigtoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9EZwuD8UZ02S4-48YhAc2Ixf9z3Ge7Wc',
    appId: '1:619732410479:web:802a531f720831654d2d9a',
    messagingSenderId: '619732410479',
    projectId: 'bigtoy-dde0f',
    authDomain: 'bigtoy-dde0f.firebaseapp.com',
    storageBucket: 'bigtoy-dde0f.appspot.com',
    measurementId: 'G-21YD65RYJ4',
  );
}
